[32m2024-04-09 22:31:19 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6afbdd2d-0a82-4b28-bb7c-94a3a8f465fe - 67363 - LOGS_CAPTURED - Started capturing logs in process (pid: 67363).
[32m2024-04-09 22:31:19 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6afbdd2d-0a82-4b28-bb7c-94a3a8f465fe - 67363 - taxi_trips_file - STEP_START - Started execution of step "taxi_trips_file".
[32m2024-04-09 22:31:36 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 6afbdd2d-0a82-4b28-bb7c-94a3a8f465fe - 67363 - taxi_trips_file - STEP_FAILURE - Execution of step "taxi_trips_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips_file"::

NameError: name 'constants' is not defined

Stack Trace:
  File "/opt/miniconda3/lib/python3.8/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/opt/miniconda3/lib/python3.8/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
  File "/opt/miniconda3/lib/python3.8/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/opt/miniconda3/lib/python3.8/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/djm/projects/data_projects/de-projects/orchestration/dagster_university/dagster_university/assets/trips.py", line 19, in taxi_trips_file
    constants.TAXI_TRIPS_TEMPLATE_FILE_PATH.format(month_to_fetch), "wb"
[0m
